# Generated by Django 2.2.6 on 2019-11-17 10:41

import chessApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=50)),
                ('player2', models.CharField(max_length=50)),
                ('winner', models.CharField(default='Draw', max_length=50)),
                ('timeout_in', models.TimeField(default=chessApp.models.gametimedefault)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
